### ISSUE TITLE
What the means of a in x, y, w, h, a = ann['bbox']

### ISSUE THREAD

**Issue by fuqianya** [ccccwb/Multimodal-Detection-and-Tracking-UAV#2]
Hi,

Thanks for your great work! I have a question regarding the variable a in `x, y, w, h, a = ann['bbox']`. Could you please clarify what a represents?

Additionally, could you kindly release the `annotations/val_mod_illumination.json` file?

Thank you!

**Comment by ccccwb** [comment]
a is the angle.

you can refer to this repository: https://github.com/VisDrone/DroneVehicle
